site_name: Phenolyzer 
site_url: https://readthedocs.org/projects/phenolyzer/
repo_url: https://github.com/WangGenomicsLab/phenolyzer
repo_name: GitHub
site_description: Phenolyzer documrntation
site_author: Hui Yang, et al
site_favicon: favicon.ico
copyright: 2010-2015 Hui Yang

docs_dir: .
include_search: true
#use_absolute_urls: true
#use_directory_urls: false

pages:

